### ISSUE TITLE
17.0.1模拟器长按选中某一行划线闪退！

### ISSUE THREAD

**Issue by dedencwzy** [coderWeil/WLReader#3]
15Pro   17.0.1模拟器 长按划线会闪退 是因为单例bookModel为空 强解包了。

<img width="1015" alt="image" src="https://github.com/coderWeil/WLReader/assets/154294156/8bd3329e-1c8f-43ae-b4d9-073f962b122b">
<img width="486" alt="image" src="https://github.com/coderWeil/WLReader/assets/154294156/2880d574-5fd3-4bc6-a7e0-cb15552ce8f7">

**Comment by coderWeil** [comment]
这个需要自己手动改一下，在解析书籍之后，将书籍模型赋值给单例中，由于这个是demo，主要是阅读功能，笔记相关的模块提供的是实现思路
在这里
![截屏2024-07-16 09 28 43](https://github.com/user-attachments/assets/49620d94-6e69-43c4-af6e-bf168cd16f50)

**Comment by dedencwzy** [comment]
> 这个需要自己手动改一下，在解析书籍之后，将书籍模型赋值给单例中，由于这个是demo，主要是阅读功能，笔记相关的模块提供的是实现思路 在这里 ![截屏2024-07-16 09 28 43](https://private-user-images.githubusercontent.com/14228146/348904865-49620d94-6e69-43c4-af6e-bf168cd16f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTM3NDUsIm5iZiI6MTcyMTA5MzQ0NSwicGF0aCI6Ii8xNDIyODE0Ni8zNDg5MDQ4NjUtNDk2MjBkOTQtNmU2OS00M2M0LWFmNmUtYmYxNjhjZDE2ZjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDAxMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDMyMjE0NTNlN2RjZjdhNzJmNGIwN2RiYjUwNWVlNmE4OTkxZjExNDY0MTViZDZiOTY3ODllMWI5NDA3OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lV1vdgUuQiggGLUQ9nkyygXW6GyT1HMW034e4-v_ajo)

非常感谢，学习了

**Comment by coderWeil** [comment]
最新的代码已更新，可以下载demo查看下，多谢支持
