### ISSUE TITLE
可以商用吗

### ISSUE THREAD

**Issue by ZClee128** [coderWeil/WLReader#4]

**Comment by coderWeil** [comment]
可以的

**Comment by coderWeil** [comment]
> 项目做的不错， 可以商用的可以把具体的开源协议加上，然后再折腾下把 Pod 和 SPM 支持给加上，会有不少人用。

感谢认可，做成pod或者spm有些麻烦，如果是单纯的阅读内容还好，涉及到笔记划线，评论等一些业务强相关的场景，无法在阅读器统一处理。目前还没有好的思路来做，有好的思路可以讨论下
